### ISSUE TITLE
MVP: User can see the current location of vehicles on map 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can find the location of all their vehicles on a single map.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create page with a map on it. Pull simulation GPS data. Make some of them moving. Make some of them stopped.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133002273-15fad635-9d82-49d2-9dac-047ce2d9902b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create dummy route for a few vehicle  (3-7 vehicles seems like a good amount)
  - [x] Json file for each with like 20-30 points (to start)

### 🐘 Database

- [x] Create current location for vehicle in vehicles table 
- [x] Create json field in vehicles table to store dummy route, dailyRoute
- [x] Put dummy route code in data.sql 

### ☁️ Server

- [x] Create get code
  - [x] Pull dummy route from dailyRoute field 

### ⚡ Client

- [x] Create map code
- [x] Create <Marker /> for each vehicles 
- [x] Making them move
  - [x] Create function to get fetch 
  - [x] Get number of coords for counter 
  - [x] Parse coords into vehicle state property 
  - [x] Create setInterval() in componentDidUpdate()

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
