### ISSUE TITLE
MVP: User can attach a photo of the vehicle 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a picture to the vehicle's profile. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On vehicle profile, photobox will have no photo, an upload button, and save button. Pressing upload will prompt a user to select a photo from there computer. Clicking save will save it then show the picture. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133527615-7430774b-f9e7-4eaf-944e-3b1cf0d0e900.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create put consume
  - [x] Takes vehicleId and image url 
  - [x] Save image URL to photo field in vehicles table 

### ⚡ Client

- [x] Create box
- [x] Create upload and save buttons 
- [x] Add file upload code 
- [x] Make put request to save photo url in file system to photo field in vehicles table 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.
