### ISSUE TITLE
MVP: User can enter vehicle specs (nickname, make, model, year, plate, color )

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter relevant information to keep track of vehicles in their fleet 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On Vehicle profile, user can press the pen icon. The fields will appear as text field. User then enters text and presses the save button. The new text shows displays. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/132604634-f65c0225-ca29-43f2-a7ad-1628c364aaaa.png)
![image](https://user-images.githubusercontent.com/11698908/132604696-3295d53d-a347-4a93-991c-16d8d95ac0ab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Look at entered values with gui tool 

### ☁️ Server

- [x] Create post request code 
  - [x] Enter values into database 
- [x] Create get request code 
  - [x] Retrieve values from database 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create box for text in vehicle profile component 
  - [x] Create edit view with editable text boxes
  - [x] Create display view 
- [x] Create post request for entering values

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
