### ISSUE TITLE
MVP: User can enter driver info (name, phone, email) 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter info of the drive to remind them who is assign to that vehicle in the field. Their contact info is going to be used for notification features. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the veicle profile, user see text fields. The fields display as text fields for editing. Text is entered by the user and they press the save button. The info entered into the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/132614676-357b3c1b-1530-4114-9dca-9888a02d25a3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Make 3 initial driver values

### ☁️ Server

- [x] Create post for entering values into the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create entry view in HTML
  - [x] Create post request to server to enter value in database 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
