### ISSUE TITLE
MVP: User can see live status of each vehicle on map (driving: green dot, stopped: red dot) 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can see moving vehicles as green and stopped vehicles as red. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On Live map, red and green dots appear on map.  Vehicles stationary for more than 10 mins will be considered stopped. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133002273-15fad635-9d82-49d2-9dac-047ce2d9902b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create state prop stopped 
- [x] MovedAt
  - [x] Create state prop movedAt
  - [x] Check if current and incoming coords are the same
  - [x] if movedAt is older than 7 mins change state prop to true
- [x] Marking Green or red
  - [x] Create condition for <Marker /> if this.state.stopped === false, dot is green
  - [x] else if this.state.stopped === true, dot is red 

 [Longest light is 5min 33secs](https://www.nytimes.com/2001/06/24/nyregion/on-the-road-the-longest-light.html)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
