### ISSUE TITLE
User can see all trips for the day

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133913140-de5c9bec-7473-4390-82a9-50b01964fa95.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Enter trips into database 
  - [ ] Make sure trips table has all other attributes to work

### ☁️ Server

- [ ] Create app.get() for all trips in index.js

### ⚡ Client

- [ ] make list 
  - [ ] Pull trips from trips table with call to app.get() in index.js
  - [ ]  map() over trips 
  - [ ] Make blue box element with with start coords, stop coords, and vehicle 
- [ ] Map element 
  - [ ] Maybe make this as a component in another file 
  - [ ] send coords object to <map /> with polyline attribute

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
