### ISSUE TITLE
User can see vehicles stops for the day 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users want to see where their vehicles were through out the day. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133913188-8498ad17-e49b-419f-9999-c0424791a81d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
 
### 🐘 Database

- [x] Make sure database is ready to do the job
- [x] Enter sample data
 
### ☁️ Server

- [x] Create app.get() in index.js to get all trips
 

### ⚡ Client

- [x] make list 
  - [x] Pull stops from stop table with call to app.get() in index.js
  - [x]  map() over stops
  - [x] Make code: calculate the duration of stop from beginTIme and endTime
  - [x] Make blue box element with with stop coords, vehicle
- [x] Map element 
  - [x] Maybe make this as a component in another file 
  - [x] send coords object to <map /> marker object 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
