### ISSUE TITLE
MVP: User can view driver info (name, phone, email) 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#25]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view info of the drive to remind them who is assign to that vehicle in the field. Their contact info is going to be used for notification features. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the veicle profile, user looks in the right hand corner and there it lay. A holy trinity: Name, phone, email. Amen

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/132897378-f8e5b327-ce08-46d5-88d4-2cef75f19a99.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Create app.get() to pull driver information from database 

### ⚡ Client

- [ ] Create blue box to view driver, phone, email
### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
