### ISSUE TITLE
MVP: User can create a route for the day for a vehicle 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a route on a map that can be sent to the driver of the vehicle by 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User sees map. They can drop one pin at a time on the map.  A line connect the drops in the order they were dropped. They can then select text or email to send a link to the driver

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/132614529-e9ed281f-89e8-495d-96a7-a0cf080283dd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Make map 
- [x] Make pin drop functionality 
- [x] Pin drop 
  - [x] Make pin drop: adding lat/lng to state, updating in <marker />
  - [x] Mulitple pins: add more marker with lat/lng using .map()
- [x] Add a number label over the pin 
- [x]  Make link creation with google maps api from lat/lng object in state 
- [x]  Display vehicle name at top  

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
