### ISSUE TITLE
MVP: User can update vehicle photo on vehicle profile

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#32]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update a picture to the vehicle's profile. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the vehicle's profile, when the user hovers the mouse over the box for the vehicle picture a pen icon will appear the corner.. Clicking it will present a prompt in the box "Upload photo" and  "Save"  buttons. Clicking it will present a window to select a file from the users' machine. User can then click save. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133668630-213e4ac1-d024-47eb-b20d-fb25d662794f.png)
![image](https://user-images.githubusercontent.com/11698908/133668660-f05e20ca-8d18-45a4-9df4-81475802e2bc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Add to vehicle app.get(), get photo url 

### ⚡ Client

- [ ] Displaying photo
  - [ ] In Get call, get photo url when page loads. 
  - [ ] Make photo display in photo box 
- [ ] Updating photo
  - [ ] Make div clickable
  - [ ] Clicking shows gradieant over photo and upload/save buttons

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
