### ISSUE TITLE
MVP: User can edit driver info

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#35]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change and update driver information 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User sees pen icon in top right of box. They press it and the text fields change to edit fields. They enter text and press save. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133664556-154d65bd-f745-4085-831f-d6c56f4d6374.png)
![image](https://user-images.githubusercontent.com/11698908/133664573-43e8233c-b5f6-4c45-8fd4-b49b37195ad4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Create app.put() for vehicleId and insert updated field name, phone, email

### ⚡ Client

- [ ] Add pen icon to display code
  - [ ] make it show the edit field 
- [ ] Make save button send updated fields to app.put()

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
