### ISSUE TITLE
MVP: User can view vehicle info

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#36]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see name, make, model, year, color, plate. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User arrives at vehicle-profile and sees them there 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133667406-0c3682b9-6a9e-44c7-ba0b-e5fcf3a5743f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create app.get() that pulls vehicle from vehicles table based on vehicleId 

### ⚡ Client

- [ ] Create blue box 
  - [ ] Make fields in wireframe
- [ ] Make get call to server 
- [ ] Display database fields returned in text fields 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
