### ISSUE TITLE
MVP: User can edit vehicle info 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#37]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter new information into vehicle fields

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User see the text displayed in the box. They click the pen icon. The fields change to text inputs with existing values displaying. They can change the values or leave them the same. They click the save button and the field change back to static text. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133666756-6c02e77a-dccd-4f8b-b4ce-63ce094c0b5f.png)
![image](https://user-images.githubusercontent.com/11698908/133666787-4c93cfae-756b-4f53-b5a9-d1039ff00501.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Create app.put() to update the fields. 
### ⚡ Client

- [ ] Put pen icon in blue box
  - [ ] Make change to edit view when pressed
- [ ] Make save button call put when pressed 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
