### ISSUE TITLE
MVP: User can navigate between pages 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#38]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click links in nav menu to go to different pages. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User see nav menu. Clicking on link will take them to that page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133669465-1748f1e5-63b3-47b7-9921-76adf4b4fe27.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] make purple nav menu like wireframe
- [x] Nav between pages with hash routing 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
