### ISSUE TITLE
MVP: User can view list of vehicles 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#39]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a list of all vehicles and click one to see vehicle profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133673708-7bd89b83-516f-414c-b8ba-b8170eb13313.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create field current location in vehicles table

### ☁️ Server

- [x] Create app.get() to get all vehicles list 
  - [x] Get currentLocaiton, name, make, model

### ⚡ Client

- [x] Create list view 
- [x] Create file vehicles-list.js
  - [x] Call get() in server to get fields 
  - [x] Create blue box to display text like wireframe
  - [x] Put server data through map() to popluate a list 
- [x] make hash routing with vId go to vehicle profile 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
