### ISSUE TITLE
MVP: User can send route to their driver via text 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a route that their driver will open on their phone to follow for the day via text 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After they create a route with the "user can create route" feature they can select text and press the send button. The driver's phone number is in their vehicle's profile page. They will receive a link that can be opened in google maps with the selected stops as destinations in the tip. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List
![image](https://user-images.githubusercontent.com/11698908/132921861-72b59fc4-71ed-49db-bd1c-44c708be7058.png)

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a file and class for text utility
- [x] Get twilio sending a text in js file
- [x] Make formatted text with blank name, driver, and link text
- [x] Pass link, name, and driver as props to component 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
