### ISSUE TITLE
MVP: User can enter their phone number 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#40]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can put their phone number into text box and get text for the remainder of the session. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133669717-97385347-6c17-4438-99a5-7b48135cd607.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Make app.put() to enter phone into the admin user

### ⚡ Client

- [x] Add settings link to nav 
- [x] Make setting page with blue box
  - [x]  Pull from users table, username, firstname, lastname, email, phone
  - [x] make save button
- [x] Push to app.put()
  - [x] make handleSubmit
  - [x] save button calls handleSubmit onclick
  - [x] Format phone number to +15555555555
- [x] Make call to app.put() to update phone field for admin user

### 🧑‍⚕️ Clean Up
- [x] Make sure all user notifcations are pull from database and not hard coded

###  

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
