### ISSUE TITLE
User can see individual stop

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#49]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see stop locaiton, duration, and google map of stop

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Move from stops list to trip profile with stopId in url> gets stop via api> displays field in blue box> display trip in live map 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

none 

### ☁️ Server

- [x] Make get() for stop with stopId input 

### ⚡ Client

- [x] Create stops profile page
- [x] Create blue box with fields stop location, duration, and vehicle
- [x] Add <Map /> that displays the stop location coords
- [x] Update hash route in app.js 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
