### ISSUE TITLE
MVP: User can receive copy of route via text

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can receive a copy of the route link along with the driver's name and vehicle name. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A text comes to their phone with a link, driver's name, and vehicles name. Clicking the link will open the route in google maps

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Get user phone from database
- [x]  Format text with driver, vehicle, and link
- [x] Use Twilio method to send text 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
