### ISSUE TITLE
Design Update: Remake features in Material UI Dashboard template

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#59]
## ⚙️ Feature

> ##### Which feature is affected by this update?

Make new UI using this https://www.creative-tim.com/product/material-dashboard-react?partner=104080

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Feature code can very easy me put into this template for a massive UI upgrade. 

Make updates in stages. 

Update 
1. Live Map: needs a better look with dashboard type things around it
2. List views
3. Profile views 
4. Routing 
5. Alerts
6. Settings

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![deepin-screen-recorder_chromium-browser_20211004171135](https://user-images.githubusercontent.com/11698908/135941060-b3b70bec-0eee-4487-ab50-ddefb36817a9.gif)

## Research 
- [ ] Moving npm libraries like express and dotenv

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Fill this out for the above stages
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
