### ISSUE TITLE
MVP: User can get a speeding alert via text for a vehicle 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/whereisitgps#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select to get a speeding alert when a certain speed is exceeded by a driver 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On a vehicle's profile, user clicks the Alerts button. The check the box next to Speeding and click save. Then they will receive an alert (via text and/or email via their check respective check boxes) with the driver's name, vehicle name, the speeding threshold for the vehicle, and top speed reached. The threshold will only fire once after the threshold is crossed. However it will fire again if the vehicle drops below threshold and then crosses it again. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/11698908/133353418-b230b2e0-541d-4589-b98f-13c34317d425.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Make demo field as bool on vehcles table
- [x] Make top speed field 
- [x] Make speeding field 
 
### ☁️ Server

- [x]  Post info back to database
  - [x] Create post comsume updating alerts in database 

### ⚡ Client

 - [x] Make vehicle-alert page
   - [x]  Make basic layout
   - [x] Clean up css
   - [x] Box like wireframe
 - [x] Get request for /api/vehicleinfo/:vId
   - [x] Create speeding field populates speeding text box
- [x] Checks speeding field against top speed field 
  - [x ] Checks if demo field is true 
  - [x] if so, checks if top speed field is greater than speeding field 
  - [x] If so, post request to /api/sentext with message with driver,  vehicle, and speed 
  - [x] Make separate method for text and email, 
  - [x] Pass arguments to them with message
- [x]  Post info back to database
  - [x] Create post call to database to insert new values 

### 🧑‍⚕️ Clean Up

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by rskidmore1** [comment]
.

**Comment by rskidmore1** [comment]
.
